# Generated by Django 5.2.3 on 2025-09-30 13:06

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finalparticipant",
            name="address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="finalparticipant",
            name="contact",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="finalparticipant",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="finalparticipant",
            name="id_proof",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="id_proofs/",
            ),
        ),
        migrations.AlterField(
            model_name="finalregistration",
            name="author_address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="finalregistration",
            name="author_contact",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="finalregistration",
            name="author_designation",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="finalregistration",
            name="author_gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="finalregistration",
            name="author_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="visitorregistration",
            name="id_proof_file",
            field=models.FileField(
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="identity_proofs/",
            ),
        ),
    ]
