# Generated by Django 5.2.3 on 2025-10-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0002_alter_finalparticipant_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="abstractsubmission",
            options={},
        ),
        migrations.RemoveField(
            model_name="abstractsubmission",
            name="category",
        ),
        migrations.RemoveField(
            model_name="abstractsubmission",
            name="mode_of_participation",
        ),
        migrations.RemoveField(
            model_name="coauthor",
            name="category",
        ),
        migrations.AddField(
            model_name="abstractsubmission",
            name="ACCOMMODATION",
            field=models.CharField(
                choices=[("REQUIRED", "REQUIRED"), ("NOT-REQUIRED", "NOT REQUIRED")],
                default="NOT-REQUIRED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="abstractsubmission",
            name="FOOD_PREFERENCE",
            field=models.CharField(
                choices=[("NON-VEG", "VEG"), ("NON-VEG", "VEG")],
                default="VEG",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="coauthor",
            name="ACCOMMODATION",
            field=models.CharField(
                choices=[("REQUIRED", "REQUIRED"), ("NOT-REQUIRED", "NOT-REQUIRED")],
                default="NOT-REQUIRED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="coauthor",
            name="FOOD_PREFERENCE",
            field=models.CharField(
                choices=[("NON-VEG", "VEG"), ("NON-VEG", "VEG")],
                default="VEG",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="abstractsubmission",
            name="designation",
            field=models.CharField(
                choices=[
                    ("Student", "Student"),
                    ("Research Scholar", "Research Scholar"),
                    ("Assistant Professor", "Assistant Professor"),
                    ("Associate Professor", "Associate Professor"),
                    ("Professor", "Professor"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="abstractsubmission",
            name="institute",
            field=models.CharField(
                choices=[
                    ("Assam University, Silchar", "Assam University, Silchar"),
                    ("Others", "Others"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="coauthor",
            name="designation",
            field=models.CharField(
                choices=[
                    ("Student", "Student"),
                    ("Research Scholar", "Research Scholar"),
                    ("Assistant Professor", "Assistant Professor"),
                    ("Associate Professor", "Associate Professor"),
                    ("Professor", "Professor"),
                ],
                max_length=100,
            ),
        ),
    ]
